config/routes.rb
Rails.application.routes.draw do
  get 'rounds/show'
#    Prefix Verb URI Pattern        Controller#Action
#   pages_about GET  /about(.:format)   pages#about
# pages_contact GET  /contact(.:format) pages#contact
#          root GET  /                  pages#home
  devise_for :users, controllers: { registrations: 'users/registrations' }
  root to: 'pages#home'

  resources :decks, only: [:show, :new, :create, :index, :edit, :destroy]

  resources :cards, only: [:show, :new, :create, :index, :edit, :destroy]

  resources :rounds, only: :show

  get 'dashboard', to: 'dashboard#show'

  # cards_show GET    /cards/show(.:format)  cards#show
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
  has_many :decks, through: :deck_cards
  # validates...
end

app/models/deck.rb
class Deck < ApplicationRecord
  belongs_to :user
  has_many :deck_cards
  has_many :cards, through: :deck_cards

  # validates...
end

app/models/deck_card.rb
class DeckCard < ApplicationRecord
  belongs_to :decks
  belongs_to :cards
  has_many :rounds
end

app/models/round.rb
class Round < ApplicationRecord
  has_many :cards, through: :deck_cards
  has_many :decks, through: :deck_cards
  belongs_to :deck_cards
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base


end

app/controllers/cards_controller.rb
# frozen_string_literal: true

class CardsController < ApplicationController
  # skip_before_action :authenticate_user!
  def index
    @cards = Card.all
  end

  def new
    @card = Card.new
    # @deck = Deck.find(params[:deck_id])
  end

  def create
    @card = Card.new(card_params)
    # @deck = Deck.find(params[:deck_id])
    # @card.deck = @deck
    if @card.save
      redirect_to cards_path
    else
      render :new
    end
  end

  def show
    @card = Card.find(params[:id])
  end


  def edit
    @card = Card.find(params[:id])
  end

  def update
    @card = Card.find(params[:id])
    if @card.update(card_params)
      redirect_to cards_path
    else
      render :new
    end
  end

  def destroy
    @card = Card.find(params[:id])
    @card.destroy
    redirect_to cards_path
  end


  private

  def card_params
    params.require(:card).permit(:word, :translation, :hint, :deck_id)
    # params.require(:card).permit(:word, :translation, :hint, :photo, :deck_id)
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  # skip_before_action :autheticate_user!
  def show
   # all decks will be shown
  end
end

app/controllers/decks_controller.rb
class DecksController < ApplicationController
  # skip_before_action :authenticate_user!
  def index
    @decks = Deck.all
  end

  def new
    @deck = Deck.new
  end

  def create
    @deck = Deck.new(deck_params)
    @deck = Deck.find(params[:deck_id])
    if @request.save
      redirect_to requests_path
    else
      render :new
    end
  end

  def show
    @deck = Deck.find(params[:id])
    @card = Card.find(params[:id])
    # @card = @card
  end


  def edit
    @deck = Deck.find(params[:id])
  end

  def update
     @deck = Deck.find(params[:id])
    if @deck.update(card_params)
      redirect_to cards_path
    else
      render :new
    end
  end

  def destroy
    @deck = Deck.find(params[:id])
    @deck.destroy
    redirect_to cards_path
  end

  private

  def deck_params
    params.require(:deck).permit(:name)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/controllers/rounds_controller.rb
class RoundsController < ApplicationController
  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cards/edit.html.erb
<h1>Cards#edit</h1>




 <a href="" class ="">
  <%= link_to "Show all cards", cards_path, class: 'btn btn-primary button-action create-deck-button'%>
</a>


 <a href="" class ="">
  <%= link_to "Save changes", cards_path, class: 'btn btn-primary button-action create-deck-button'%>
</a>


 <div class="info">

    <%= link_to "Delete", card_path(@card.id), class: 'btn btn-primary modul', method: :delete, data: { confirm: "Are you sure?" } %>
  </div>

app/views/cards/index.html.erb
<h1>Cards#index</h1>


<ul>
  <% @cards.each do |card| %>
  <li><%= link_to card.id, card_path(card) %></li>
  <% end %>
  <br></br>

<a href="" class ="">
  <%= link_to "Back", dashboard_path, class: 'btn btn-primary button-action create-deck-button'%>
</a>

app/views/cards/new.html.erb
<h1>Cards#new</h1>

<p>Create a new card right here</p>



<div class="cards_new_wrap">
    <%= simple_form_for [@card] do |f| %>
    <div class="form-group">
    <%= f.input :word, as: :string, required: false, wrapper_html: {class: "requests_input"}, placeholder: 'Word' %>

     <%= f.input :translation, as: :string, required: false, wrapper_html: {class: "requests_input"}, placeholder: 'Translation'%>
     <%= f.input :hint, as: :text, required: false, wrapper_html: {class: "requests_input"}, placeholder: 'Hint' %>

    <%= f.input :deck_id, as: :integer, required: false, wrapper_html: {class: "requests_input"}, placeholder: 'Deck number' %>

   </div>
    <div class="butu d-flex justify-content-around align-items-baseline">
      <%= f.submit "Save", id: 'sweet-alert-save', class: 'btn btn-primary new-card button-action' %>
      <%= link_to "Cancel", dashboard_path, id:'Cancel'%>
    </div>
    <% end %>
</div>





<!--
input fields:
- word
-translation
-hint
-deck name

 field to click in for pictre
 - open module to either upload from user or google search

save btn
cancel btn

  -->

app/views/cards/show.html.erb
<h1>Cards#show</h1>
<p>Show a card right here</p>

<h2><%= @card.word%></h2>
<div>
  <ul>
    <li>Translation: <%= @card.translation %></li>
    <li>Hint: <%= @card.hint %></li>
  </ul>
</div>



<a href="" class ="">
  <%= link_to "Back", cards_path, class: 'btn btn-primary button-action create-deck-button'%>
</a>

<a href="" class ="">
  <%= link_to "Edit", edit_card_path, class: 'btn btn-primary button-action create-deck-button'%>
</a>

app/views/dashboard/show.html.erb
<h1>Dashboard#show</h1>





<a href="" class ="">
  <%= link_to "Create a new Card", new_card_path, class: 'btn btn-primary button-action create-card-button'%>
</a>

<a href="" class ="">
  <%= link_to "Create a new Deck", new_deck_path, class: 'btn btn-primary button-action create-deck-button'%>
</a>




 <a href="" class ="">
  <%= link_to "Show all cards", cards_path, class: 'btn btn-primary button-action show-cards-button'%>
</a>


 <a href="" class ="">
  <%= link_to "Show all Decks", decks_path, class: 'btn btn-primary button-action show-decks-button'%>
</a>

app/views/decks/edit.html.erb
<h1>decks#edit</h1>



 <a href="" class ="">
  <%= link_to "Show all decks", decks_path, class: 'btn btn-primary button-action show-decks-button'%>
</a>


 <a href="" class ="">
  <%= link_to "Save changes", decks_path, class: 'btn btn-primary button-action create-deck-button'%>
</a>


 <div class="info">

    <%= link_to "Delete", deck_path(@deck.id), class: 'btn btn-primary modul', method: :delete, data: { confirm: "Are you sure?" } %>
  </div>

app/views/decks/index.html.erb
<h1>decks#index</h1>


<ul>
  <% @decks.each do |deck| %>
  <li><%= link_to deck.id, deck_path(deck) %></li>
  <% end %>
  <br></br>

<a href="" class ="">
  <%= link_to "Back", dashboard_path, class: 'btn btn-primary button-action create-deck-button'%>
</a>

app/views/decks/new.html.erb
<h1>Decks#new</h1>

<a href="" class ="">
  <%= link_to "Save Card", dashboard_path, class: 'btn btn-primary button-action save-button'%>
</a>

<a href="" class ="">
  <%= link_to "Cancel", dashboard_path, class: 'btn btn-primary button-action cancel-button'%>
</a>

app/views/decks/show.html.erb
<h1>Decks#show</h1>

<h2><%= @deck.name %></h2>


 <a href="" class ="">
  <%= link_to "Show all decks", decks_path, class: 'btn btn-primary button-action back-button'%>
</a>


 <a href="" class ="">
  <%= link_to "Edit this deck", edit_deck_path, class: 'btn btn-primary button-action edit-deck-button'%>
</a>


 <a href="" class ="">
  <%= link_to "Play", round_path, class: 'btn btn-primary button-action create-deck-button'%>
</a>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Landing page</h1>

<a href="" class="">
<%= link_to "Get Started", dashboard_path, class: 'btn btn-primary button-action start-button'%>
</a>

app/views/rounds/show.html.erb
<h1>Rounds#show</h1>

 <a href="" class ="">
  <%= link_to "Cancel", decks_path, class: 'btn btn-primary button-action create-deck-button'%>
</a>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Messages", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>